# VMW-Jira environment: jira-lvnv-it-101/102/103
environment: VMW-Jira
app_type: jira
domain: .lvn.broadcom.net

servers:
  - jira-lvnv-it-101
  - jira-lvnv-it-102
  - jira-lvnv-it-103

paths:
  dbconfig: /export/jirahome/dbconfig.xml
  jira_home: /export/jirahome
  setenv: /export/jira/bin/setenv.sh
  access_log_dir: /export/jira/logs
  app_log_file: /export/jirahome/log/atlassian-jira.log

ssh_user: svcjira
app_port: 8080
